apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: github-project-sync-run
spec:
  template:
    spec:
      taskCount: 3
      template:
        spec:
          containers:
            - env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: '2'
                      name: github-project-sync-github-token
              image: us-west1-docker.pkg.dev/knowledgework-simenyan-sandbox/github-project-sync/app:20250115-172601
              resources:
                limits:
                  cpu: 1000m
                  memory: 512Mi
          maxRetries: 3
          serviceAccountName: sa-cloud-run-ghpsync@knowledgework-simenyan-sandbox.iam.gserviceaccount.com
          timeoutSeconds: '600'
