apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: github-project-sync
spec:
  template:
    spec:
      template:
        spec:
          containers:
            - env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: '1'
                      name: github-project-sync-github-token
                - name: GITHUB_PROJECT_NUMBER
                  value: '9'
                - name: GITHUB_ORG
                  value: 'knowledge-work'
              command:
                - '/bin/ghpsync'
              image: us-west1-docker.pkg.dev/knowledgework-simenyan-sandbox/github-project-sync/app:20241109-190153
              resources:
                limits:
                  cpu: 1000m
                  memory: 512Mi
          maxRetries: 3
          serviceAccountName: sa-cloud-run-ghpsync@knowledgework-simenyan-sandbox.iam.gserviceaccount.com
          timeoutSeconds: '600'
